language: go
go:
- 1.5
before_script:
- npm install -g n
- n stable
- pushd js2
- npm install
- npm build
- npm test
- popd
notifications:
  slack:
    on_failure: always
    on_success: change
    on_start: never
    secure: j7d7CnXYDRjfWfiLHJwFYqiE5QoNFuwp9sXv3w+pH9FzTF+t7bBndo8R4cTh5oJZcVobzGZDwJcnp41fzWuAbXMdXfWU6uLlRATQ4vqTkL3t+iNtux2XXv0OBVwARRBmKhI+vTlZD5nScPsMAL4op4CC7wQGOzIwCaWvcVe+TAzrBhIVwGG65DMUFlg8Ta0zLE1c/d+G3IVY4tuYGQeyawrJ3Xt5tziqT/nBjolyEsPTrVJp3eQ/AsYSCHRj7s51MU02Q6tXzU071qWLzjVxLm2EPU1l7Ck4JUO2CwQCSDj9U4J41Dv4adwTmIZojHT7lcZpLJzRYRvQWrEWB4NUCpCaiOLtFo4qRtnF0FYuI5um4nybmjAqvnTCYn5kCmsF6FByo1IRJX5GKnpbDVcPEk2E6txJYEQWDvilnfwhx9qJ+uhBlIKCgBZGM73p0/Wr+fdGO7VQbjcCoPkXoYhRvLF1k7pYoknjHYhPfgvWfeTvo4JPMwE167Q2Q4bFvXr0BOmtQcIPPRqOObst/A2RmKt4AN0nWywnhKw4+dqJcq5N8GIXrscCOx5kwqOXa0VwDJNQC7iku9HrMO/h5TcJmfb90w4wBc29m8Yeqca0/Q1bRysolqS9QN5A+YXzlDUci6uVScVsGldog+3TC7cW9S6SyocpPNaN4w/ulcJWQew=
