language: go
go:
- 1.5
before_script:
- npm version
- nvm install stable
- nvm use stable
- npm version
- pushd js2
- npm install
- npm test
- popd
- pushd clients/splore
- npm install
- ./link.sh
- npm run build
- npm test
- popd
- pushd clients/pitchmap/ui
- npm install
- ./link.sh
- npm run build
- npm test
- popd
script:
- export GODEBUG=invalidptr=0
- go test ./...
notifications:
  email:
    recipients:
      - aa@attic.io # has email rules to filter out PRs then forward to slack
    on_failure: always
    on_success: change
    on_start: never
