on: [push]

jobs:
  mysql_client_integrations_job:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test mysql client integrations
        uses: ./.github/actions/mysql-client-tests # Uses an action in the root directory
