on:
  push:
    branches:
      - 'db/add-ses-email-action'

jobs:
  test-emailer:
    runs-on: ubuntu-18.04
    name: Test Emailer
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Send Email
        uses: ./.github/actions/ses-email-action
        with:
          region: us-west-2
          toAddresses: '["dustin@dolthub.com"]'
